runs:
  using: "composite"
  steps:
    - name: Create manifest for install Wazuh stack
      shell: bash
      run: |
        hostname=$(sudo puppetserver ca list --all | awk '{if(NR>1)print $1;}'| sed 's/[.]$//')
        sudo cat <<EOF | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        \$discovery_type = 'single-node'
        stage { 'certificates': }
        stage { 'repo': }
        stage { 'indexerdeploy': }
        stage { 'securityadmin': }
        stage { 'dashboard': }
        stage { 'manager': }
        Stage[certificates] -> Stage[repo] -> Stage[indexerdeploy] -> Stage[securityadmin] -> Stage[manager] -> Stage[dashboard]
        Exec {
            timeout => 0,
        }
        node "$hostname" {
            class { 'wazuh::certificates':
                indexer_certs => [['node-1','127.0.0.1']],
                manager_certs => [['master','127.0.0.1']],
                dashboard_certs => ['127.0.0.1'],
                stage => certificates,
            }
            class { 'wazuh::repo':
                stage => repo,
            }
            class { 'wazuh::indexer':
                stage => indexerdeploy,
            }
            class { 'wazuh::securityadmin':
                stage => securityadmin
            }
            class { 'wazuh::manager':
                stage => manager,
            }
            class { 'wazuh::filebeat_oss':
                stage => manager,
            }
            class { 'wazuh::dashboard':
                stage => dashboard,
            }
        }
        EOF


    - name: Install Wazuh Stack
      shell: bash
      run: sudo bash -c 'puppet agent -tod || test $? -eq 2'